"""Host-reception to WS-dispatch latency; never subtract clocks across machines."""
import math


def action_frame_timing(metadata, sent_ms, source):
    result = {'action_source': source, 'ws_action_send_ms': sent_ms, 'frame_age_ms': {}}
    # Human commands are not generated by the model observation. A zero handoff
    # poll also deliberately carries no policy metadata.
    if source != 'policy' or sent_ms is None or not metadata:
        return result
    stamps = metadata.get('frame_received_ms', {})
    for view in ('side', 'wrist'):
        stamp = stamps.get(view)
        if isinstance(stamp, (int, float)) and math.isfinite(stamp):
            age = sent_ms - stamp
            if age >= 0:
                result['frame_age_ms'][view] = age
    result['frame_received_ms'] = dict(stamps)
    result['buffer_sequence'] = metadata.get('buffer_sequence')
    return result
